### ISSUE TITLE
File permissions problems when updating /opt/jboss/wildfly/domain/configuration/application-users.properties after we added OpenShift support

### ISSUE THREAD

**Issue by ppalaga** [l2x6/calculator-ws#10]
This happens in camel Quarkus main `38f4e54e0818d91629c176262111279242b96d05` after #9:

```
cd integration-test-groups/cxf-soap/cxf-soap-client
mvnd clean test -Dtest=CxfSoapClientTest#basicAuthClient
```

```
2023-05-03 11:29:23,200 INFO  [🐳 .io/.1]] (pool-2-thread-1) Creating container for image: quay.io/l2x6/calculator-ws:1.1
2023-05-03 11:29:23,294 INFO  [🐳 .io/.1]] (pool-2-thread-1) Container quay.io/l2x6/calculator-ws:1.1 is starting: c8fa87f0c432fda916e340b49b4503d6b50e606de1f00f3f0c5c773d5bc43b7f
2023-05-03 11:29:23,726 INFO  [org.tes.con.wai.str.HttpWaitStrategy] (pool-2-thread-1) /heuristic_kapitsa: Waiting for 60 seconds for URL: http://localhost:32768/calculator-ws/CalculatorService?wsdl (where port 32768 maps to container port 8080)
2023-05-03 11:29:24,470 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
2023-05-03 11:29:24,475 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT:  * Error * 
2023-05-03 11:29:24,476 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: WFLYDM0106: File permissions problems found while attempting to update /opt/jboss/wildfly/domain/configuration/application-users.properties file.
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: Exception in thread "main" org.jboss.as.domain.management.security.adduser.AddUserFailedException: WFLYDM0106: File permissions problems found while attempting to update /opt/jboss/wildfly/domain/configuration/application-users.properties file.
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.ErrorState.execute(ErrorState.java:72)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.AddUser.run(AddUser.java:133)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.as.domain-management@18.1.1.Final//org.jboss.as.domain.management.security.adduser.AddUser.main(AddUser.java:233)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Module.run(Module.java:353)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Module.run(Module.java:321)
2023-05-03 11:29:24,477 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDERR: 	at org.jboss.modules.Main.main(Main.java:604)
2023-05-03 11:29:24,800 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: =========================================================================
2023-05-03 11:29:24,805 INFO  [org.apa.cam.qua.com.cxf.soa.cli.it.CxfClientTestResource] (docker-java-stream--834586101) STDOUT: 
```

It is caused by the recent change https://github.com/l2x6/calculator-ws/pull/9 in the test container by @llowinge I'll have to revert it. 

I am going to reset 1.1 to the state before #9 and will set up 1.2 branch with #9 merged. @llowinge would you please then find a solution for 1.2?

**Comment by ppalaga** [comment]
> I am going to reset 1.1 to the state before https://github.com/l2x6/calculator-ws/pull/9 and will set up 1.2 branch with https://github.com/l2x6/calculator-ws/pull/9 merged.

All done, the two containers are being deployed:

* 1.1 https://github.com/l2x6/calculator-ws/actions/runs/4872248472
* 1.2 https://github.com/l2x6/calculator-ws/actions/runs/4872240275

**Comment by llowinge** [comment]
I'm working at fix.
